-- phpMyAdmin SQL Dump
-- version 5.1.1deb5ubuntu1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Mar 19, 2023 at 11:19 AM
-- Server version: 8.0.32-0ubuntu0.22.04.2
-- PHP Version: 8.1.2-1ubuntu2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `vidyarthiadda_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `college_details`
--

CREATE TABLE `college_details` (
  `ID` int NOT NULL,
  `time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` varchar(200) NOT NULL,
  `state` varchar(200) NOT NULL,
  `dist` varchar(200) NOT NULL,
  `city` varchar(200) NOT NULL,
  `course` varchar(200) NOT NULL,
  `code` varchar(200) NOT NULL,
  `yearofest` int NOT NULL,
  `approval` varchar(200) NOT NULL,
  `offered` varchar(200) NOT NULL,
  `highpkg` varchar(200) NOT NULL,
  `avgpkg` varchar(200) NOT NULL,
  `image` varchar(400) NOT NULL,
  `about` varchar(10000) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `recr` varchar(10000) NOT NULL,
  `NIRF` varchar(10000) NOT NULL,
  `NAAC` varchar(10000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `college_details`
--

INSERT INTO `college_details` (`ID`, `time`, `name`, `state`, `dist`, `city`, `course`, `code`, `yearofest`, `approval`, `offered`, `highpkg`, `avgpkg`, `image`, `about`, `recr`, `NIRF`, `NAAC`) VALUES
(6, '2022-11-25 15:16:23', 'Mangalmay group of institutions', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nMBA++,\r\nBBA,\r\nB.COM,\r\nBCA,\r\nB.PHARMA,\r\nD.PHARMA,\r\nB.TECH\r\n', 'MN6789,\r\nNM6789,\r\nI12345,\r\nA12345,\r\nM12345,\r\nE12345,\r\nU12345,\r\nF12345\r\n', 2002, 'AICTE, NAAC', 'Private', '37 LPA', '8 LPA', 'http://vidyarthiadda.com/images/MANGALMAY.jpg', 'Established in 2002, Mangalmay Group of Institutions is one of the premier NAAC accredited Institution with a prime focus on Innovation, Excellence and Nurturing global leaders for a sustainable future. We incorporate Knowledge, Industry experience, Research, and International exposure in our curriculum, to offer comprehensive educational program to the students. The post graduate and graduate programmes offered at Mangalmay are affiliated to AKTU, Lucknow (formally known as U.P.Technical University) and approved by the All India Council for Technical Education (AICTE) Ministry of HRD, New Delhi. Institute is also affiliated to C.C.S University Meerut.', '', '', ''),
(7, '2022-11-25 15:24:32', 'Noida institute of engineering and technology', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nPGDM,\r\nMCA,\r\nB.TECH,\r\nM.TECH\r\n', 'MN6789,\r\nAX6789,\r\nFS6789,\r\nF12345,\r\nUV6789\r\n', 2001, 'NAAC - A, PCI, UGC', 'UG, PG', '48 LPA', '4.25 LPA', 'http://vidyarthiadda.com/images/NIET.jpg', 'NIET is one of the premier Engineering and Management institutes of India\'s National Capital Region (NCR). It was established by eminent visionaries, responsible for setting up City Educational & Social Welfare Society of Meerut, with a vision to provide value driven education of global dimensions. The institute is managed by City Educational & Social Welfare Society, which runs several prestigious educational and health organizations, viz. NIET (Noida Institute of Engineering & Technology), CVPS (City Vocational Public School), Pyramid Finishing School, Dayanand Nursing Home, Chandra Sen Charitable Hospital & Om Diagnostic Center.\r\nNoida Institute of Engineering and Technology, a self-financed institute, offering high standard quality education to students from all corners of the country, is situated in Greater Noida (a hub of global MNCs). The institute has a sprawling area of 13.90 acres and lush green ambience all around.', '', '', ''),
(8, '2022-11-25 15:35:58', 'GNIOT Group of institutions ', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nPGDM,\r\nBBA,\r\nB.COM,\r\nBCA,\r\nMCA,\r\nB.TECH,\r\nM.TECH,\r\nBBA\r\n', 'MN6789,\r\nAX6789,\r\nI12345,\r\nA12345,\r\nM12345,\r\nFS6789,\r\nF12345,\r\nUV6789,\r\nI12345\r\n', 2001, 'AICTE, NAAC', 'UG, PG', '17.75 LPA', '4.50 LPA', 'http://vidyarthiadda.com/images/GNIOT.jpg', 'Greater Noida Institute of Technology (GNIOT) is one of the premier Institutions in the field of Technical and Management Education. It has been formed by Shri Ram Educational Trust, Noida on no profit basis with a firm determination and commitment to foster a holistic approach towards the development of Engineering and Management Education. The Trust was formed in the year 2000 and the Institute was established in the year 2001. The Trust has had a meteoric rise, and on date, has established a chain of educational institutions covering the fields of engineering and management leading towards Graduate and Post Graduate degrees. Plans are also afoot to introduce Doctoral Programmes in the very near future. It has been approved by AICTE, Ministry of HRD, Goverment of India and affiliated to Dr. A.P.J. Abdul Kalam Technical University, Lucknow The Institute distinguishes itself from other colleges and Institutes due to its holistic approach and unique foresighted planning in providing technical and professional education with the state-of-the-art techniques. The main objective of an Institute is to generate a bunch of highly creative professionals, who can contribute not only in the Human Resource Development but also in the Nation Building Exercise.', '', '', ''),
(9, '2022-11-25 15:39:18', 'GN Group', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nPGDM,\r\nBBA,\r\nB.COM,\r\nBCA,\r\nB.PHARMA,\r\nD.PHARMA,\r\nLAW,\r\nB.TECH,\r\nBBA\r\n', 'MN6789,\r\nAX6789,\r\nI12345,\r\nA12345,\r\nM12345,\r\nE12345,\r\nU12345,\r\nAB6789,\r\nF12345,\r\nI12345\r\n', 2008, 'AICTE, NAAC', 'UG, PG', '19 LPA', '3.5 LPA', 'http://vidyarthiadda.com/images/GNGROUP.jpg', 'GN Group has two decades old legacy of imparting quality education in multidiscipline.\r\n\r\nIt has been a pioneer of world class education and is carrying on the rich tradition of bringing about world class facilities, best teaching learning practices and state of the art facilities. It has a history of having outstanding alumni who are the leaders of their work spheres.\r\n\r\nGN Group of Institutes is one of the largest educational groups based in Greater Noida, having large strength of students spread across the country. It has energetic, dedicated and highly qualified faculty members from IITs, NITs, IIITs, IIMs and other reputed institutes and universities.', '', '', ''),
(10, '2022-11-25 15:44:53', 'Accurate institute of management and technology ', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nPGDM,\r\nBBA,\r\nB.COM,\r\nBCA,\r\nB.PHARMA,\r\nD.PHARMA,\r\nLAW,\r\nB.TECH,\r\nBBA\r\n', 'MN6789,\r\nAX6789,\r\nI12345,\r\nA12345,\r\nM12345,\r\nE12345,\r\nU12345,\r\nAB6789,\r\nF12345,\r\nI12345\r\n', 2006, 'AICTE', 'UG PG', '19 LPA', '6.4 LPA', 'http://vidyarthiadda.com/images/ACCURATE.jpg', 'Accurate Institute of Management & Technology (AIMT) is one of the many prestigious institutions functioning under the aegis of Accurate Group of Institutions. The Accurate Group of Institutions was incepted in the year 2006 under Accurate Education & Research Society. Demonstrating meteoric growth since beginning it has become one of the prominent educational groups solely devoted to equip thousands of young students in the diversified fields, i.e. Management, Engineering Technology, Architecture and Diploma Courses.\r\n\r\nThe PGDM Course offered by Accurate Institute of Management & Technology (Greater Noida) is duly approved by AICTE, Ministry of HRD, Govt. of India. The institute is ranked amongst Top B schools by various agencies and has been rising and creates a niche in the ever expanding management horizon. Dr. S.K. Datta, a graduate from IIM-Kolkata, is the torch bearer as Director General nearing 3 decades of global experience in blue chip multinationals & institutions like IIT Kharagpur, IMT Ghaziabad, VIT Business School.', '', '', ''),
(11, '2022-11-25 15:57:45', 'UNITED Group of institute ', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nBBA,\r\nB.COM,\r\nBCA,\r\nB.PHARMA,\r\nD.PHARMA,\r\nB.TECH,\r\nBBA', 'MN6789,\r\nI12345,\r\nA12345,\r\nM12345,\r\nE12345,\r\nU12345,\r\nF12345,\r\nI12345\r\n', 2005, 'AICTE', 'UG, PG', '20 LPA', '5.20 LPA', 'http://vidyarthiadda.com/images/UNITED.jpg\r\n', 'United Institutes works on the motto of holistic education of its students. Hence every measure is taken that their progress does not remain constrained to the classrooms. Ample scope for extracurricular activities along with classroom syllabus keeps the student at par with the best of the institutes. The campuses are located away from the city, landscaped stunningly to create a peace of mind and make the environment academically inductive.\r\n\r\nSpecial care is given to the courses of the student which demand industrial trainings and visit. The Naini industrial area provides the perfect opportunity for the students to gain hands on experience and getting to know the grooves of the industry. The Greater Noida campus has a great advantage of being in the NCR-region which is the home ground of the corporate giants making it simpler for the students to gain a practical work experience along with classroom education. At United we believe in taking the course of progress in the fields of technology and administration to the pinnacle. Hence our motto remains nurturing the young minds today, who will create history tomorrow.', '', '', ''),
(12, '2022-11-25 16:01:29', 'GL bajaj group of instituton ', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nPGDM,\r\nBBA,\r\nBCA,\r\nMCA,\r\nB.TECH,\r\nM.TECH,\r\nBBA', 'MN6789,\r\nAX6789,\r\nI12345,\r\nM12345,\r\nFS6789,\r\nF12345,\r\nUV6789,\r\nI12345\r\n', 1997, 'AICTE, NAAC', 'UG, PG', '54 LPA', '4.50 LPA', 'http://vidyarthiadda.com/images/GLBAJAJ.jpg', 'GL Bajaj Institute of Technology and Management is one of the quality driven Educational Institute in the Greater Noida/Delhi-NCR Region. GL Bajaj stands out as one of the best engineering and management college in UP. It also stands out in its approach to assist and equip the students for their overall development, giving them a strong foundation for a successful future. The institute offers B.Tech, MBA and MCA programs.\r\n\r\nThis self financed institute is governed by Rajeev Memorial Academic Welfare Society (Registered Under Societies Registration Act 1860). It is approved by All India Council for Technical Education (AICTE), Ministry of Human Resource Development, Government of India and affiliated to Dr. A.P.J. Abdul Kalam Technical University, Lucknow. The institute has been maintaining its positions amongst the top engineering and management colleges in AKTU university results. It has been maintaining the highest pass percentage amongst the engineering and Management colleges in Noida and Greater Noida region under Dr. APJ Kalam University, Lucknow for the last eight years and is listed among the top engineering and management colleges in Greater Noida, Delhi NCR. In fact this engineering college has been listed among the top engineering of India by NIRF, issued by MHRD, Government of India. The Institute has also received awards for being one of the top engineering and management institutes of North India and UP by many organizations.', '', '', ''),
(13, '2022-11-25 16:05:03', 'LLOYD Group of Institutions ', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nPGDM,\r\nBBA,\r\nB.COM,\r\nBCA,\r\nMCA,\r\nLAW,\r\nB.TECH,\r\nM.TECH,\r\nBBA', 'MN6789,\r\nAX6789,\r\nI12345,\r\nA12345,\r\nM12345,\r\nFS6789,\r\nAB6789,\r\nF12345,\r\nUV6789,\r\nI12345\r\n', 2004, 'AICTE, PCI', 'UG, PG', '20 LPA', '6 LPA', 'http://vidyarthiadda.com/images/LLOYD.jpg', 'Lloyd Business School has been operational since 2004, guided by the philosophy of combining theoretical knowledge with practical applications in order to create skilled, highly trained and employable professionals.\r\n\r\nLloyd constantly strives to achieve its objective of delivering quality education to students while ensuring their professional development. The strength of the Institute lies in the niche and highly industry-integrated courses that Lloyd offers in the field of management under the combined aegis of renowned faculty members and highly respected corporate professionals. The PGDM programs offered in the field of Human Resources, Supply Chain Management and Business Analytics jointly with industry leaders like the Manpower Group, Safeducate and IBM.', '', '', ''),
(14, '2022-11-25 16:08:07', 'Amity University ', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nMBA++,\r\nPGDM,\r\nBBA,\r\nB.COM,\r\nBCA,\r\nMCA,\r\nB.TECH,\r\nM.TECH,\r\nBBA\r\n', 'MN6789,\r\nNM6789,\r\nAX6789,\r\nI12345,\r\nA12345,\r\nM12345,\r\nFS6789,\r\nF12345,\r\nUV6789,\r\nI12345\r\n', 2005, 'NIL', 'UG, PG', '22 LPA', '4.8 LPA', 'http://vidyarthiadda.com/images/AMITY.jpg', 'Amity believe in grooming leaders who are not only thorough professionals but also good human beings with values and sanskars. At Amity we benchmark only against the best institutions around the world. Our faculty and senior team travel all over the globe to learn and imbibe the best practices so that we can give a solid foundation for learning.\r\n\r\nAs part of this endeavour, we have air-conditioned amphitheatre style classrooms that provide the most conducive atmosphere for dynamic and focused discussions, while the libraries at our campus are equipped with over 1,00,000 books, periodicals, national and international journals, CD-ROMS, covering all aspects of academic studies and research material. The hi-tech labs act as ideal training grounds for budding professionals that allow students to experiment and bring to practice what they have learnt in theory.', '', '', ''),
(15, '2022-11-25 16:12:52', 'KCC Institute of management and technology', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nPGDM,\r\nB.TECH,\r\nM.TECH\r\n', 'MN6789,\r\nAX6789,\r\nF12345,\r\nUV6789\r\n', 2009, 'AICTE', 'UG, PG', '19 LPA ', '4.50 LPA', 'http://vidyarthiadda.com/images/KCC.jpg', 'The foundation of the Group was laid by Late Shri R.R. Aggarwal, an eminent philanthropist of his time in the year 1951. And thereafter, Late Shri G.P. Gupta continued with the rich tradition of the Group of imparting quality and affordable education.\r\nOver the last six decades, the KCC Institutes has been actively involved in quality dispensation of technical and higher education on pan-India basis through on-line and network education. The Group has also been credited for innovating virtual methods of dissemination of education in collaboration with various State Universities.', '', '', ''),
(16, '2022-11-25 16:16:47', 'Galgotiya educational institution', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nPGDM,\r\nB.TECH,\r\nM.TECH', 'MN6789,\r\nAX6789,\r\nF12345,\r\nUV6789\r\n', 1999, 'AICTE', 'UG, PG', '12.40 LPA', '3.86 LPA', 'http://vidyarthiadda.com/images/GALGOTIYASUNIV.jpg', 'Every year Galgotias Educational Institutions (GEI) admissions are conducted for the students on the basis of cut off declared by Galgotias Educational Institutions (GEI). At Shiksha.com you can find Galgotias Educational Institutions (GEI) 2022 cut offs, for all 15 courses offered by the college. Cut off data available on Shiksha will help you to apply for B.E. / B.Tech,MBA/PGDM,M.E./M.Tech,MCA courses in Galgotias Educational Institutions (GEI), Greater Noida', '', '', ''),
(17, '2022-11-25 16:19:35', 'Innovative college of pharmacy ', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'B.PHARMA,\r\nD.PHARMA,\r\nM.PHARMA\r\n', 'E12345,\r\nU12345,\r\nDE6789\r\n', 2006, 'AICTE, PCI ', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/INNOVATIVE.jpg', 'It is a non-profit, quality conscious and trend-setting Pharmacy Institute in Greater Noida with focus on providing equal opportunities for development of human potentials of every segment of society including the differentiated one.\r\nThe Innovative College of Pharmacy has been established through the dedicated and selfless endeavor of educationists and social workers who are deeply concerned with the standards of education and are determined to upgrade the quality, content and direction of education. The Innovative College of Pharmacy is a venture of its kind where educators and professionals have joined hands to aid and direct the agenda of education. The Innovative College of Pharmacy is located in the institutional area of Greater Noida and has a magnificent building.', '', '', ''),
(18, '2022-11-25 16:23:04', 'Spectrum Institute of pharmaceutical sciences and research', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'B.PHARMA,\r\nD.PHARMA,\r\nM.PHARMA\r\n', 'E12345,\r\nU12345,\r\nDE6789\r\n', 2008, 'AICTE, PCI', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/SPECTRUM.jpg', 'Spectrum Institute of Pharmaceutical Science and Research (SIPSAR) was established in 2008 under the aegis of Delhi International Educational Society with the aim of providing quality higher education, at par with international standards. SIPSAR is located in Knowledge Park I (Greater Noida) within walking distance from the Pari chowk metro station. SIPSAR seeks and adopts innovative practices and best of resources and standards to improve the quality of higher education consistently. Our Memoranda of Understanding with various Pharmaceutical companies are our major strength. Our consistent aim is to provide the nation with Industry-ready brilliant professionals. Our core team of Experienced and learned teachers are strongly encouraged to nurture the students into well- rounded individuals. The highly motivated youngsters on the campus are a constant source of pride. Many of our students bring high quality to their work and esteem to our Nation and have done us proud. With steady steps, we continue our march forward. We look forward to meeting you here at SIPSAR.', '', '', ''),
(19, '2022-11-25 16:25:46', 'Trinity institute of innovations in professional studies ', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'BBA,\r\nBCA,\r\nLAW,\r\nB.TECH,\r\nBBA\r\n', 'I12345,\r\nM12345,\r\nAB6789,\r\nF12345,\r\nI12345\r\n', 2008, 'BCI, AICTE', 'UG', '3.60 LPA', 'NA', 'http://vidyarthiadda.com/images/TRINITY.jpg', 'Trinity Institute of Innovations in Professional Studies established under the agis of Eveready Exim, a company under section 8(5) of companies ACT 2013, is one of the qualities driven Educational Institute in the Greater Noida/Delhi-NCR Region. TIIPS stands out in its approach to assist and equip the students for their overall development, giving them a strong foundation for a successful future. The institute offers B.Tech, BALLB, BBA, BCA and BJMC professional courses. It is duly approved by All India Council for Technical Education (AICTE), Ministry of Human Resource Development and Government of India.', '', '', ''),
(20, '2022-11-25 16:29:41', 'IILM University', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nPGDM,\r\nBBA,\r\nBCA,\r\nLAW,\r\nB.TECH,\r\nM.TECH,\r\nBBA', 'MN6789,\r\nAX6789,\r\nI12345,\r\nM12345,\r\nAB6789,\r\nF12345,\r\nUV6789,\r\nI12345\r\n', 2001, 'AICTE, NBA ', 'UG, PG ', '18 LPA', '8 LPA ', 'http://vidyarthiadda.com/images/IILM.jpg', 'IILM University offers a holistic and integrated approach to learning across a broad range of subjects; Engineering, Liberal Arts, and Management. Our global and national outreach supports us by over 30 academic collaborations. We aim to nurture the next generation of thought leaders as engaged citizens adding meaningful contributions to society. IILM has a strong alumni network of more than 15000 alumni. Their success stories play a pivot role in making IILM as a preferred choice for students of Delhi NCR and other parts of the country.The University has been consistent in facilitating superior quality education. IILM’s integrated and experiential MBA curriculum is in alignment with the leading US B-Schools. The Ed Universal ranked IILM as 11th among the best Indian business schools in 2015. Its various institutes have been consistently ranked among the best B- Schools in the country. IILM’s long belief and efforts to prepare global managers with cross-cultural training have become a benchmark for management institutes across the globe and therefore it is counted amongst the best private universities in Delhi NCR.', '', '', ''),
(21, '2022-11-25 16:32:32', 'Birla institute of management and technology', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'PGDM', 'AX6789\r\n', 1998, 'AICTE, NBA, AIU, AACSB', 'UG, PG ', '18 LPA', '10 LPA', 'http://vidyarthiadda.com/images/BIM.TECH.jpg', 'The fully residential campus of Birla Institute of Management Technology (BIMTECH) located in National Capital Region is one of the top MBA Institutes to study in India.', '', '', ''),
(22, '2022-11-25 16:38:33', 'IIMT Group of colleges ', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nBBA,\r\nB.COM,\r\nBCA,\r\nLAW,\r\nB.TECH,\r\nBBA\r\n', 'MN6789,\r\nI12345,\r\nA12345,\r\nM12345,\r\nAB6789,\r\nF12345,\r\nI12345\r\n', 1994, 'NAAC, PCI, BCI, NBA, AICTE', 'UG, PG ', '16 LPA', '6.50 LPA', 'http://vidyarthiadda.com/images/IIMT.jpg', 'Since its inception, the group has grown leaps & bounds and achieved exemplary recognition from the Industry & Academia. At IIMT, we are committed to provide a value driven culture along with creating a professional environment. IIMT as a group, large and diversified, imparts knowledge in the field of Engineering, Management, Education, Law, Pharmacy, etc. It has highly qualified and experienced faculty members in their respective functional areas. IIMT boasts of having more than 8,000 students in various courses in six colleges.\r\n The educational group has been dedicated towards providing quality professional education through well-accredited courses, Seminars, Conferences, Guest Lectures, Industrial visits and excellent Academic facilities. We believe in an all round development of students with strong foundation based on pillars of knowledge, intellect and values. The programs are structured to keep pace with the present dynamic and globalized scenario meeting the requirement of industry and education. We are dedicated to deliver excellence in our academic programs.', '', '', ''),
(23, '2022-11-25 16:40:54', 'I Business Institute', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'PGDM', 'AX6789\r\n', 2008, 'AICTE', 'PG', '18 LPA', '6.50 LPA', 'http://vidyarthiadda.com/images/IBI.jpg', 'I Business Institute (hereinafter referred to as IBI), is a well-reputed Management Institute strategically located in the knowledge hub of NCR thereby opening up a plethora of opportunities for the budding managers.', '', '', ''),
(24, '2022-11-25 16:43:56', 'Ishan Institute of management and technology', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'BBA,\r\nB.COM,\r\nBBA,\r\nB.ED\r\n', 'I12345,\r\nA12345,\r\nI12345,\r\nC12345\r\n', 1994, 'AICTE, NCTE, AIU', 'UG, PG', '11 LPA', '5 LPA', 'http://vidyarthiadda.com/images/ISHAN.jpg', 'Ishan Institute of Management and Technology is known as ISHAN INSTITUTE. It was established in 1994 by Dr. D. K. Garg He established this institution with the vision to achieve excellence in the educational field. The aim of the Institute is to provide business education or commerce education is that area of education which develops the required knowledge, skills and attitudes for the successful handling of trade, commerce and industry. At present scenario commerce education is business education. But, in tune with the needs of the business and society, independent professions have emerged in the form of chartered accountant, cost and works accountant, company secretary and business administrator (MBA). Thus, the cream of commerce has gone and it remained now as an academic discipline giving general and liberal education. Institute vision to groom the students through self-learning, presentations for developing analytical mind and pragmatic approach in the field of commerce and missions to train and equip the future CA, entrepreneur, Manager etc to Ishan Institute the emerging challenges of education in 21st century with dedication, compassion and discipline.', '', '', ''),
(25, '2022-11-25 16:46:40', 'Ram-Eesh group institutions ', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'polytechnic,\r\nB.PHARMA,\r\nD.PHARMA,\r\nB.TECH,\r\nM.PHARMA\r\n', 'CS6789,\r\nE12345,\r\nU12345,\r\nF12345,\r\nDE6789\r\n', 1997, 'AICTE, PCI, NBA ', 'UG, PG', '8 LPA', '3.5 LPA ', 'http://vidyarthiadda.com/images/RAMEESH.jpg', 'Ram-Eesh Group of Institutions have been established under the aegis of Rama-Eesh Charitable Trust. The foundation stone was laid by the Chairman on November 21, 1997 and the Institutions were inaugurated by the former Governor of U. P., Late Shri Vishnukant Shastri on September 04, 2001. Ram-Eesh Group of Institutions consist of an International School providing education from nursery to Class XII; an Institute of Education providing B.Ed; an Institute of Vocational and Technical Education providing D.Pharmacy and B.Pharmacy: and an Institute of Engineering & Technology providing Diploma in Computer Science Engineering, Electronics and Communication Engineering, Civil Engineering & Mechanical Engineering.', '', '', ''),
(26, '2022-11-25 16:49:12', 'Government institute of medical science (GIMS)', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBBS,\r\nDNB\r\n', 'XY6789,\r\nW12345\r\n', 2016, 'MCI', 'NA', 'NA', 'NA', 'http://vidyarthiadda.com/images/GIMS.jpg', 'Government Institute of Medical Sciences, Greater Noida, is an apex institute with mission to provide affordable health services to all sections of the society and has been envisioned to be in the forefront of providing excellent professional medical education, multi-disciplinary research and state of the art tertiary care medical facilities.', '', '', ''),
(27, '2022-11-25 16:52:08', 'Sharda University', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nBBA,\r\nB.COM,\r\nBCA,\r\nB.TECH,\r\nBBA,\r\nMBBS', 'MN6789,\r\nI12345,\r\nA12345,\r\nM12345,\r\nF12345,\r\nI12345,\r\nXY6789\r\n', 1996, 'NCTE, DCI, COA, INC, MCI, BCI, UGC', 'UG, PG', '7 CR', '8.50 LPA', 'http://vidyarthiadda.com/images/SHARDA.jpg', 'Sharda University is a leading Educational institution based out of Greater Noida, Delhi NCR. A venture of the renowned Sharda Group of Institutions (SGI), The University has established itself as a high quality education provider with prime focus on holistic learning and imbibing competitive abilities in students. The University is approved by UGC and prides itself in being the only multi-discipline campus in the NCR, spread over 63 acres and equipped with world class facilities. Sharda University promises to become one of the India\'s leading universities with an acknowledged reputation for excellence in research and teaching. With its outstanding faculty, world class teaching standards, and innovative academic programmes, Sharda intends to set a new benchmark in the Indian education system.', '', '', ''),
(28, '2022-11-25 16:54:44', 'Bennett University', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nBBA,\r\nB.COM,\r\nBCA,\r\nLAW,\r\nB.TECH,\r\nBBA', 'MN6789,\r\nI12345,\r\nA12345,\r\nM12345,\r\nAB6789,\r\nF12345,\r\nI12345\r\n', 2016, 'BCI,UGC', 'UG, PG', '63 LPA', '17 LPA', 'http://vidyarthiadda.com/images/BENETT.jpg', 'The Times Group established Bennett University in 2016 with a vision to provide quality education and establish itself as one of the best private universities in India to impart interdisciplinary education. It was established by the Act of the State Legislature of Uttar Pradesh as a private university. The six schools with 30+ programs and 70+ leading specialisations in Engineering, Management, Media, Law and Liberal Arts have positioned it as one of the top universities in India. This has made it a sought-after destination for fortune companies and leading corporates in a short period, picking talents with prominent placement records.', '', '', ''),
(29, '2022-11-25 16:57:29', 'Noida international university', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nBBA,\r\nBCA,\r\nLAW,\r\nB.TECH,\r\nBBA', 'MN6789,\r\nI12345,\r\nM12345,\r\nAB6789,\r\nF12345,\r\nI12345\r\n', 2010, 'NCTE, COA, INC, BCI, AICTE, UGC', 'UG, PG', '4.80 LPA', '6 LPA', 'http://vidyarthiadda.com/images/NIU.jpg', 'Noida International University is established by U.P. LEGISLATURE ACT NO. 27 OF 2010 and under Section 2(f) of the UGC Act, 1956. A world Class University sponsored by the Maruti Educational Trust. The lush green campus of 75 acres with its uniquely designed architecture stands out as an infrastructure. The campus is strategically located near the Yamuna Expressway educational hub in Gautam Budh Nagar, Greater Noida. The University through its 12 schools is offering various multi-disciplinary  programmes in varied streams of Engineering, Management, Law, Medical and Social Sciences. The students from more than 54 Nations place faith in the educational curriculum of the University. The Petals leading towards a star is an embodiment of the University cherished mission to provide education beyond the boundaries and to felicitate the students and faculty to achieve pinnacles of success throughout the world.', '', '', ''),
(30, '2022-11-25 17:00:44', 'Indian institute of finance', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'BBF,\r\nEMBF,\r\nFBA,\r\nMBF,\r\nPGPM,\r\nSTRA', 'L12345,\r\nX12345,\r\nY12345,\r\nDJ6789,\r\nKD6789,\r\nMB6789\r\n', 1987, 'AICTE, UGC', 'PG', '12 LPA', '3.50 LPA', 'http://vidyarthiadda.com/images/IIF.jpg', 'IIF established in 1987 as a non-profit autonomous research based equity educational institution to promote education & research in Finance. IIF has made distinguished scholarly contributions - acclaimed nationally and internationally. IIF is unique and is the only organisation of its kind in India. It is an Island of Excellence in Finance. IIF Alumni holds senior positions in Banks, Financial Institutions, Corporate, Governments & Academia. IIF Signed 45+ MOUs with Universities Worldwide.', '', '', ''),
(31, '2022-11-25 17:04:08', 'Harlal institute of management and technology', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'MBA,\r\nBBA,\r\nBCA,\r\nBBA,\r\nB.ED', 'MN6789,\r\nI12345,\r\nM12345,\r\nI12345,\r\nC12345\r\n', 1998, 'AICTE', 'UG, PG', '12 LPA', '6 LPA', 'http://vidyarthiadda.com/images/HARLAL.jpg\r\n', 'HIMT Group of Institutions was established in the year 1998 by the same enlightened group of people from a cross section of society who had joined together & formed the Shanti Educational Society, registered under the registration Act.XXI, of 1980.The basic philosophy of HIMT is based on the fabric of Eastern thinking and Western concepts. To achieve this goal, the group has targeted the imparting of a global perspective to the young students. Since its inception, the Group has promoted Management, Computer Application, Law, Biotechnology, Pharmacy and Education Department.  HIMT started on humble grounds, recognising the importance and requirement of a rapidly changing domestic and global environment to create a niche in the education sector by imparting technical and professional education through state-of- the-art technology and teaching methodology. HIMT Group of Institutions is one of the best management institute in the region.', '', '', ''),
(32, '2022-11-25 17:09:27', 'JIMS engineering management technical campus ', 'UTTAR PRADESH ', 'GB NAGAR', 'Greater Noida', 'BBA,\r\nB.COM,\r\nBCA,\r\nLAW,\r\nB.TECH,\r\nBBA,\r\nB.ED', 'I12345,\r\nA12345,\r\nM12345,\r\nAB6789,\r\nF12345,\r\nI12345,\r\nC12345\r\n', 2013, 'AICTE', 'UG, PG', '16 LPA ', '6.50 LPA', 'http://vidyarthiadda.com/images/JIMS.jpg', 'Jagan Nath Gupta Memorial Educational Society is a registered non-profit organization imparting high quality professional education to create a pool of professionally qualified and skilled managers and entrepreneurs to meet the growing needs of trade and industry. The society has performed a stellar role in spreading education in science and management in India by establishing a number of campuses in Delhi and Jaipur. The students after completing their courses successfully take up the role of entrepreneurs or join industry and business as professionals. They are readily accepted by both the public and private sectors in India and abroad.', '', '', ''),
(33, '2022-11-25 17:12:39', 'Asian Business School ', 'UTTAR PRADESH ', 'GB NAGAR', 'Noida ', 'PGDM,\r\nMBA\r\n', 'AX6789,\r\nMN6789\r\n', 2011, 'AICTE, NBA, AIU ', 'PG', '17.30 LPA', '6.50 LPA', 'http://vidyarthiadda.com/images/ASIAN.jpg', 'Asian Business School is an innovative centre of academic excellence approved by AICTE and is one of the top colleges for PGDM / MBA in India. The flagship PGDM degree program offered here is accredited by the National Board of Accreditation (NBA) and granted equivalence to the MBA Degree of an Indian University by the Association of Indian Universities (AIU).', '', '', ''),
(34, '2022-11-25 17:15:37', 'Amity Global Business School ', 'UTTAR PRADESH ', 'GB NAGAR', 'Noida ', 'MBA,\r\nPGDM,\r\nBBA,\r\nBBA\r\n', 'MN6789,\r\nAX6789,\r\nI12345,\r\nI12345\r\n', 2008, 'NA', 'UG, PG', '26 LPA', '10 LPA', 'http://vidyarthiadda.com/images/AMITYGLOBAL.jpg', 'We continually take the time to work with you personally to help you reach your goals. We employ our proven CORE Principle to structure all study goals and exam formats, as well as learning and teaching methods, to make studying enjoyable and help you achieve the best possible outcome in your studies. In doing so, our university received the Genius Loci Award for Excellence in Teaching from Stifterverband and the Volkswagen Foundation in 2018.', '', '', ''),
(35, '2022-11-25 17:18:35', 'Jaipuria Institute of Management ', 'UTTAR PRADESH ', 'GB NAGAR', 'Noida ', 'MBA,\r\nPGDM\r\n', 'MN6789,\r\nAX6789\r\n', 2004, 'AICTE, NBA, AIU', 'PG', '19.10 LPA', '10.10 LPA', 'http://vidyarthiadda.com/images/JAIPURIA.jpg', 'One of the most respected and dedicated business groups of the country, the house of Jaipuria has acquired a place and stature of its own in the industrial and educational arena.\r\n\r\nJaipuria legacy of education began in 1945 with the establishment of the Jaipuria College in Calcutta (now Kolkata) by the great visionary and educationist Padma Bhushan Seth Anandram Jaipuria, It is this unique heritage spanning 7 decades and 4 generations that sets us apart from other educational institutes.\r\n\r\nSince then we have grown parallel in school as well as in postgraduate management education.', '', '', ''),
(36, '2022-11-25 17:21:13', 'Institute of management studies ', 'UTTAR PRADESH ', 'GB NAGAR', 'Noida ', 'MBA,\r\nPGDM,\r\nBBA,\r\nBCA,\r\nLAW,\r\nBBA', 'MN6789,\r\nAX6789,\r\nI12345,\r\nM12345,\r\nAB6789,\r\nI12345\r\n', 1998, 'UGC', 'UG, PG ', '17 LPA ', '6.50 LPA', 'http://vidyarthiadda.com/images/IMS.jpg', 'IMS NOIDA, one of the trusted Business Schools in India with 33 years of academic legacy offers PGDM programme which is approved by AICTE and accredited by the National Board of Accreditation (NBA) and equivalent to MBA by Association of Indian Universities (AIU). The Institute is also accredited globally by ASIC, U.K, and is a proud member of AACSB Business Education Alliance, USA.', '', '', ''),
(37, '2022-11-25 17:23:52', 'Hierank business school (HBS)', 'UTTAR PRADESH ', 'GB NAGAR', 'Noida ', 'MBA,\r\nBBA,\r\nBCA,\r\nBBA,\r\nB.ED', 'MN6789,\r\nI12345,\r\nM12345,\r\nI12345,\r\nC12345\r\n', 2006, 'AICTE', 'UG, PG ', '22 LPA ', '3.20 LPA ', 'http://vidyarthiadda.com/images/HIERANK.jpg', 'Hierank Business School (HBS) is a private Business School established in 2006. It is located at Noida, Uttar Pradesh, and is approved by AICTE. The institute offers BBA, BCA, B.Ed. at the UG level and MBA, PGPHA at the PG level. BBA, BCA, B.Ed. programs are affiliated to CCS University Meerut and the MBA program is affiliated to Dr. Abdul Kalam Technical University. About 86% of students are placed in well-reputed companies every year.', '', '', ''),
(38, '2022-11-25 17:27:06', 'jaypee School of Business', 'UTTAR PRADESH ', 'GB NAGAR', 'Noida ', 'MBA', 'MN6789', 2007, 'AICTE', 'UG, PG ', '46 LPA ', '13 LPA ', 'http://vidyarthiadda.com/images/JAYPEE.jpg', 'Jaypee Business School (JBS) is the latest symbol of the vision of our Founder Chancellor Hon’ble Shri Jaiprakash Gaur ji. JBS was started in the year 2007 as a constituent of Jaypee Institute of Information Technology (Deemed University). It has made good progress in a short span and has shown a very high level of academic accomplishment. JBS has benchmarked itself with the latest content and teaching methodologies across the country.', '', '', ''),
(39, '2022-11-25 17:29:14', 'Birla Institute of Technology ', 'UTTAR PRADESH ', 'GB NAGAR', 'Noida ', 'MBA,\r\nBBA,\r\nBCA,\r\nMCA', 'MN6789,\r\nI12345,\r\nM12345,\r\nFS6789\r\n', 1998, 'AICTE', 'UG, PG ', '21 LPA ', '9.38 LPA ', 'http://vidyarthiadda.com/images/BIT.jpg', 'Established in 1955 by the visionary industrialist Mr. BM Birla, BIT Mesra was founded with a clear vision to offer its young minds a space, where their imagination could take wings and their ideas fruition. For over 6 decades now, the institute has nurtured minds with a rich heritage of academic excellence, developing learning frameworks that have been well ahead of times.', '', '', ''),
(40, '2022-11-25 17:31:51', 'Jagannath Institute of Management Science ', 'UTTAR PRADESH ', 'GB NAGAR', 'Noida ', 'BBA,\r\nB.COM,\r\nBCA,\r\nB.TECH', 'I12345,\r\nA12345,\r\nM12345,\r\nF12345\r\n', 1997, 'NA', 'UG, PG ', '12 LPA ', '3.5 LPA ', 'http://vidyarthiadda.com/images/JIMSMANAGEMENT.jpg', 'Jagannath Institute of Management Sciences was established in 1998 under the aegis of Jagannath Gupta Memorial EducationalSociety (Regd.) with a mission of creating scholars of excellence who are full of knowledge, dynamism, honesty and dedication. Our endeavor is to blend intellectual insights with personality development to suit the corporate requirements by providing high quality professional education. The Society is in the field of higher education for more than 28 years imparting quality education in different courses. The Institute is located in VasantKunj, Institutional Area, South Delhi. college. The faculty is highly experienced and most of them have industry exposure. Further value addition to the curriculum is done by Guest Speakers from industry and industry visits for the students. We at JIMS create motivated, enthusiastic young graduates who desire to learn and improve continually, welcome ideas, value diversity with a desire to succeed in all spheres of life.', '', '', ''),
(41, '2022-11-25 17:34:02', 'Institute of Technology and Science ', 'UTTAR PRADESH ', 'GB NAGAR', 'Ghaziabad', 'MBA,\r\nPGDM,\r\nMCA\r\n', 'MN6789,\r\nAX6789,\r\nFS6789\r\n', 1995, 'AICTE, NBA, AIU', 'UG, PG', '18.5 LPA ', '5.65 LPA', 'http://vidyarthiadda.com/images/ITSGHAZIABAD.jpg', 'ITS School of Management is a premier management school established in 1995 under the aegis of ITS Education Group. The institute was established with a view to imparting quality education in the field of Management and Information Technology. ITS Ghaziabad is affiliated to Dr. A.P.J. Abdul Kalam University and recognised by the UGC. The School is also accredited by the NBA and NAAC Grade ‘A’. ITS is ranked 78 among Top Private MBA institutes by Outlook – ICARE India 2020.', '', '', ''),
(42, '2022-11-25 17:36:16', 'Institute of Management Technology ', 'UTTAR PRADESH ', 'GB NAGAR', 'Ghaziabad ', 'MBA,\r\nPGDM\r\n', 'MN6789,\r\nAX6789\r\n', 1980, 'AICTE', 'PG', '63 LPA ', '15.28 LPA', 'http://vidyarthiadda.com/images/IMT.jpg', 'Established in 1980, Institute of Management Technology, Ghaziabad (IMTG) is India’s premier AACSB accredited management school with a distinct focus on grooming leadership through Innovation, Execution and Social Responsibility. An autonomous, not–for–profit institute, offering highly sought after postgraduate programmes over the past four decades, IMTG currently offers six AICTE approved programmes – Post Graduate Diploma in Management (PGDM) Full Time, PGDM Executive, PGDM Part Time, PGDM BFS (Banking & Financial Services), PGDM Dual Country Programme (DCP) and Fellow Program in Management(FPM). IMT Ghaziabad has been set up under the aegis of Lajpat Rai Educational Society (LES), a society duly registered under Societies Act 1860, Government of India.', '', '', ''),
(43, '2022-11-25 17:38:48', 'Mewar Institute of Management', 'UTTAR PRADESH ', 'GB NAGAR', 'Ghaziabad', 'BBA,\r\nB.COM,\r\nBCA,\r\nB.ED', 'I12345,\r\nA12345,\r\nM12345,\r\nC12345\r\n', 1996, 'AICTE', 'UG, PG', '15 LPA ', '6 LPA ', 'http://vidyarthiadda.com/images/MEWAR.jpg', 'Mewar Institute of Management and Mewar Law Institute were established by the Mewar Education Society, Delhi, a non-profit making body, registered under the Societies Registration Act, 1860, and comprising a group of enlightened academicians, businessmen and industrialists of repute. The Institutes are guided in their activities by an advisory board. Both the Institutes are affiliated to Ch. Charan Singh University, Meerut and have started a number of professional, traditional and career oriented courses like BBA, BCA, B.Com, B.Sc. (Maths), B.Ed., B.Lib., M.Sc. (Biotech). ', '', '', ''),
(44, '2022-11-25 17:41:10', 'ABES Engineering College Ghaziabad ', 'UTTAR PRADESH', 'GB NAGAR', 'Ghaziabad', 'MBA,\r\nMCA,\r\nB.TECH,\r\nM.TECH', 'MN6789,\r\nFS6789,\r\nF12345,\r\nUV6789\r\n', 2000, 'AICTE, UGC, NAAC ', 'UG, PG ', 'NA', 'NA', 'http://vidyarthiadda.com/images/ABES.jpg', 'ABES Engineering College, Ghaziabad is ranked 1 Engineering College among all the colleges of AKTU, Lucknow for the last 8 semesters in B.Tech - 1st-year result. The institute has one of the best placement records among all Delhi/ NCR Colleges. More than 1,253 jobs were offered to the students of 2018-19 batch and 1,260 offers (still counting) till now to the students of 2019-20 batch. ABES Ghaziabad offers degree courses in the discipline of Engineering and Management. Admissions are done on the basis of merit, entrance exams and cutoff criteria of the institute.', '', '', ''),
(45, '2022-11-25 17:43:44', 'Institute of Management Education Group of Colleges ', 'UTTAR PRADESH ', 'GB NAGAR', 'Ghaziabad', 'MBA,\r\nPGDM,\r\nBBA,\r\nB.COM,\r\nBCA,\r\nLAW', 'MN6789,\r\nAX6789,\r\nI12345,\r\nA12345,\r\nM12345,\r\nAB6789\r\n', 1994, 'NAAC', 'UG, PG', '17 LPA', 'NA', 'http://vidyarthiadda.com/images/IME.jpg', 'Institute of Management Education is a prestigious educational institution based in Ghaziabad, UP. Started in the year 1995, IME is affiliated to Abdul Kalam Technical University (AKTU).\r\n\r\nUnder its UG programs, the institute currently offers admission in BBA, BCA, B.Com. and B. Lib. degrees including an integrated program BA-LL.B. As for PG programs, IME Ghaziabad offers a PG Diploma program in management, an MBA, M.Com and a MCA program.', '', '', ''),
(46, '2022-11-25 17:46:35', 'Institute of Management Studies (IMS)', 'UTTAR PRADESH ', 'GB NAGAR', 'Ghaziabad', 'MBA,\r\nPGDM,\r\nBBA,\r\nBCA', 'MN6789,\r\nAX6789,\r\nI12345,\r\nM12345\r\n', 1990, 'NAAC', 'UG, PG ', '19 LPA ', '5.5 LPA ', 'http://vidyarthiadda.com/images/IMSGHAZIABAD.jpg', 'IMS Ghaziabad is one of the trusted Business Schools in India with 33 years of academic legacy. Established in 1990, IMS Ghaziabad is one of the Best B schools in India accredited by NBA. IMS Ghaziabad offers AICTE approved PGDM program in six specialisations as its flagship course. Admission to IMS Ghaziabad is done on CAT/ MAT/ XAT/ CMAT/ ATMA + GD and PI round + Written Aptitude test scores.', '', '', ''),
(47, '2022-11-25 17:49:11', 'HLM Business School ', 'UTTAR PRADESH ', 'GB NAGAR', 'Ghaziabad', 'MBA,\r\nBCA,\r\nLAW,\r\nB.ED', 'MN6789,\r\nM12345,\r\nAB6789,\r\nC12345\r\n', 2005, 'AICTE', 'PG', 'NA', '9 LPA', 'http://vidyarthiadda.com/images/HLM.jpg', 'HLM Group was established in 2005 by renowned businessman Mr. Sunil Miglani, CMD Migsun, in the name of his beloved father Late Shri Harbans Lal Miglani Ji (HLM).\r\nThe Group was founded, inspired by the great ancient Indian Education System, to produce ace professionals capable of taking on today’s ultra competitive environment and catalyzing change.', '', '', ''),
(48, '2022-12-11 18:04:24', 'Miranda house of college', 'DELHI', 'DELHI', 'DELHI', 'B.ED,MSC,BSC,MA,BA', 'VA27\r\nVA28\r\nVA29\r\nVA30\r\nVA14', 1948, 'NAAC', 'UG, PG', '19.25 LPA', '7.47 LPA', 'http://vidyarthiadda.com/images/MIRANDA.jpg', 'Miranda House is a constituent college for women at the University of Delhi in India. Established in 1948, it is one of the top ranked colleges of the country and ranked as number 1 for consecutively six years.', '', '', ''),
(49, '2022-12-12 06:01:09', 'Lady shri ram College for women.', 'DELHI', 'DELHI', 'DELHI', 'BA,MA,B.ED,MSC', 'VA27\r\nVA28\r\nVA14\r\nVA30', 1956, 'UGC, NAAC', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/LADYSRIRAM.jpg', 'Lady Shri Ram College for Women is a constituent women\'s college, affiliated with the University of Delhi, and has a legacy in women\'s education.\r\n\r\nLady Shri Ram College for Women is a constituent women\'s college, affiliated with the University of Delhi, and has a legacy in women\'s education.\r\n\r\nLady Shri Ram College for Women is a constituent women\'s college, affiliated with the University of Delhi, and has a legacy in women\'s education.\r\n\r\n\r\n\r\n\r\n', '', '', ''),
(50, '2022-12-12 06:06:37', 'Stephen\'s College', 'DELHI', 'DELHI', 'DELHI', 'BA,BSC', 'VA27\r\nVA29', 1881, 'UGC, NAAC', 'UG', 'NA', 'NA', 'http://vidyarthiadda.com/images/STEPHEN.jpg', 'St. Stephen\'s College is a constituent college of the University of Delhi, widely regarded as one of the oldest and most prestigious colleges for arts and sciences in India. It was established in 1881 by the Cambridge Mission to Delhi.\r\n', '', '', ''),
(51, '2022-12-12 06:09:31', 'Hindu College', 'DELHI', 'DELHI', 'DELHI', 'BA,BSC,B.COM,M.COM', 'VA27\r\nVA29\r\nVA5\r\nVA31', 1899, 'NAAC', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/HINDUCOLLEGE.jpg', 'Hindu College is a constituent college of the University of Delhi in New Delhi, India. It offers undergraduate and postgraduate programmes in sciences, humanities, social sciences and commerce. In 2022, it is ranked 2nd nationally by National Institute Ranking Framework under Ministry of Human Resource Development.\r\n\r\n\r\nHindu College is a constituent college of the University of Delhi in New Delhi, India. It offers undergraduate and postgraduate programmes in sciences, humanities, social sciences and commerce. In 2022, it is ranked 2nd nationally by National Institute Ranking Framework under Ministry of Human Resource Development.\r\n\r\n\r\n', '', '', ''),
(52, '2022-12-12 06:11:43', 'Shri ram College of commerce', 'DELHI', 'DELHI', 'DELHI', 'BA,MA,B.COM,M.COM', 'VA27\r\nVA28\r\nVA5\r\nVA31', 1956, 'NAAC, AICTE', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/SRCC.jpg', 'Shri Ram College offers various courses in Commerce, Economics and Business. These include two undergraduate programs and two post graduate programs The college has an online application process which comes under the process of University of Delhi. The criteria of admission is merit basis for undergraduate courses and entrance based for postgraduate courses. SRCC intakes students at a relatively high best of four cutoff for its undergraduate programs which usually lie above 98%.\r\n\r\n\r\n', '', '', ''),
(53, '2022-12-12 06:15:08', 'G narayanamma institute technology and science', 'HYDERABAD', 'HYDERABAD', 'HYDERABAD', 'B.TECH,M.TECH', 'VA11\r\nVA12', 1997, 'AICTE, NAAC', 'UG, PG', '4.53 LPA', 'NA', 'http://vidyarthiadda.com/images/NARAYANNAM.jpg', 'G.Narayanamma Institute of Technology & Science, “a leading Engineering college in Hyderabad for women, “was founded by late Sri G.Pulla Reddy garu in 1997, with an objective of providing excellent learning facilities for women to pursue education in Engineering since two decades. The aim is to promote Technical Education among women to enhance and build-up a new generation of thinkers.\r\n', '', '', ''),
(54, '2022-12-12 06:17:45', 'MLR institute of technology', 'HYDERABAD', 'HYDERABAD', 'HYDERABAD', 'MBA,M.TECH,B.TECH', 'VA1\r\nVA12\r\nVA11', 2005, 'AICTE, NBA, NAAC', 'UG, PG', '60 LPA', '3.15 LPA', 'http://vidyarthiadda.com/images/MLR.jpg', 'MLR Institute of Technology is located at Dundigal, Hyderabad, Telangana, India. The institution was started in 2005 by the KMR Education Trust, headed by Mr. Marri Laxman Reddy. The Institute has Six UG courses along with Seven PG Courses\r\n\r\n', '', '', ''),
(55, '2022-12-12 06:20:58', 'Muffakham jay College of engineering and technology', 'HYDERABAD', 'HYDERABAD', 'HYDERABAD', 'B.TECH,M.TECH', 'VA11\r\nVA12', 1980, 'AICTE', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/MUFFAKHAM.jpg', 'Muffakham Jah College of Engineering and Technology is an engineering college located at Mount Pleasant, Road number 3, Banjara Hills, in the heart of the city of Hyderabad in India.\r\n', '', '', ''),
(56, '2022-12-12 06:22:56', 'Vidya joyti institute of technology', 'HYDERABAD', 'HYDERABAD', 'HYDERABAD', 'B.TECH,M.TECH,MBA', 'VA11\r\nVA12\r\nVA1', 1998, 'AICTE, NAAC, NBA', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/VIDYA JOTHI.jpg', 'Vidya Jyothi Institute of Technology is a college in Hyderabad, India, established in 1998 by A.P. Jithender Reddy and V. Purushottam Reddy. It is located on the way to Chilkur Balaji Temple from Mrugavani National Park\r\n\r\n', '', '', ''),
(57, '2022-12-12 06:31:03', 'St Francis college of women', 'HYDERABAD', 'HYDERABAD', 'HYDERABAD', 'BA,BSC,B.COM,MA,MSC,BMS', 'VA27\r\nVA29\r\nVA5\r\nVA28\r\nVA30\r\nVA32', 1956, 'UGC, NAAC', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/STFRANCIS.jpg', 'St. Francis College for Women is a Catholic minority institution which is located in Begumpet, Hyderabad, Telangana, India.\r\n\r\n\r\n\r\n\r\n', '', '', '');
INSERT INTO `college_details` (`ID`, `time`, `name`, `state`, `dist`, `city`, `course`, `code`, `yearofest`, `approval`, `offered`, `highpkg`, `avgpkg`, `image`, `about`, `recr`, `NIRF`, `NAAC`) VALUES
(58, '2022-12-12 06:33:24', 'National law school of india university', 'BANGLORE', 'BANGLORE', 'BANGLORE', 'LLM,PHD,MMP,MPHILL', 'VA33\r\nVA34\r\nVA35\r\nVA36', 1986, 'BCI', 'PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/NATIONALLAW.jpg', '\"NLSIU was the first National Law University established in India in 1986. The premier law school was set up with a mission to pioneer legal education reforms, and to anchor the transformation of the Indian legal system through research and policy interventions.\r\n \r\n Consequently, the NLSIU was one of the first institutions in the country to introduce the five-year integrated law degree at the undergraduate level with the commencement of the first batch in 1988.\r\n \r\n And for over 30 years now, the University has irrefutably remained a leader in the field of legal education in the country. This long-standing record has been possible due to the strong collaborations between legal academics, the Bar, the Bench and the State Government of Karnataka.\"\r\n\r\n\r\n', '', '', ''),
(59, '2022-12-12 06:38:48', 'NIFT', 'BANGLORE', 'BANGLORE', 'BANGLORE', 'B.TECH,M.TECH', 'VA11\r\nVA12', 1986, 'AICTE', 'UG, PG', '6 LPA', 'NA', 'http://vidyarthiadda.com/images/NIFT.jpg', 'Set up in 1986, NIFT is the pioneering institute of fashion education in the country and has been in the vanguard of providing professional human resource to the textile and apparel industry. It was made a statutory institute in 2006 by an Act of the Indian Parliament with the President of India as ‘Visitor’ and has full fledged campuses all across the country\r\n', '', '', ''),
(60, '2022-12-12 06:40:49', 'Institute of hotel management', 'BANGLORE', 'BANGLORE', 'BANGLORE', 'BSC,MSC,DIPLOMA', 'VA29\r\nVA30\r\nVA37', 1969, 'NCHMCT', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/INSTITUTEOFHOTELMANAGEMENT.jpg', 'The Institute of Hotel Management, Catering Technology and Applied Nutrition, generally known as Institute of Hotel Management\r\n\r\n', '', '', ''),
(61, '2022-12-12 06:46:01', 'Madras Cristian college', 'CHENNAI', 'CHENNAI', 'CHENNAI', 'MCA,PG DIPLOMA,CERTIFICATE', 'VA7\r\nVA38\r\nVA39', 1837, 'UGC', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/MADRAS.jpg', 'Madras Christian College is a liberal arts and sciences college in Chennai, India. Founded in 1837, MCC is one of Asia\'s oldest extant colleges.\r\n\r\n', '', '', ''),
(62, '2022-12-12 06:48:36', 'Stella. Maris college', 'CHENNAI', 'CHENNAI', 'CHENNAI', 'BA,BSC,BBA,B.COM,M.COM,MSW', 'VA27\r\nVA29\r\nVA4\r\nVA5\r\nVA31\r\nVA40', 1947, 'NAAC, UGC', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/STELLA.jpg', 'Stella Maris College is an institution of higher education for women in Chennai, India. It is an autonomous college affiliated to the University of Madras and is partly residential.\r\n\r\n\r\n\r\n\r\n', '', '', ''),
(63, '2022-12-12 06:51:47', 'Bharath institute of higher education', 'CHENNAI', 'CHENNAI', 'CHENNAI', 'B.TECH,M.TECH,MBA', 'VA11\r\nVA12\r\nVA1', 1984, 'AICTE', 'UG, PG', '7 LPA', '2.4 LPA', 'http://vidyarthiadda.com/images/BHARATH.jpg', 'Bharath Institute of Higher Education and Research also known as Bharath Institute of Science and Technology, informally Bharath University, and formerly Bharath Engineering College is a private and deemed university and an Indian institute of higher education located in Chennai,\r\n\r\n', '', '', ''),
(64, '2022-12-12 06:56:32', 'Ethiraj. College for women', 'CHENNAI', 'CHENNAI', 'CHENNAI', 'BA,BSC,B.COM,BBA,BCA,MCA,MBA,M.COM', 'VA27\r\nVA29\r\nVA5\r\nVA4\r\nVA6\r\nVA7\r\nVA1\r\nVA31', 1948, 'UGC', 'UG, PG', '10 LPA', '5 LPA', 'http://vidyarthiadda.com/images/ETHIRAJCOLLEGE.jpg', 'Situated in the heart of the city of Chennai in 9 acres of campus area, the College stands self-contained with prestigious structures measuring a total plinth area of 3,48,751sq.ft. This admirable infrastructural facility and the sound vision on which the Institution is built, is upheld by the successive Managements, Principals, Faculty and Students and this has gained for the College the five star status from NAAC and the College with Potential for Excellence (CPE) award from the UGC. Thousands of students have passed out of the portals of the College, carrying with them the aura and dignity of the Institution itself. These former students today occupy enviable positions all over the world from diplomatic circles, to law and order, to teaching and caring for the under-privileged. They have also won national awards for their contribution to the nation’s cultural and educational legacy. In strengthening the core competencies, the College has been making steady progress. The College has a dedicated team of 346 faculty members who maintain academic excellence and about 7335 students who are the anchor to sustain the vision of the Institution. The College has high standards of academic excellence and a constant zeal for continuous updating and renewal of skills and knowledge.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', '', '', ''),
(65, '2022-12-12 07:01:20', 'Indian institute of technology Bombay', 'MUMBAI', 'MUMBAI', 'MUMBAI', 'B.TECH,M.TECH', 'VA11\r\nVA12', 1958, 'AICTE, UGC', 'UG, PG', '1.2 CPA', '25 LPA', 'http://vidyarthiadda.com/images/IITB.jpg', 'The Indian Institute of Technology Bombay is an internationally acclaimed autonomous public research university and technical institute in Powai, Mumbai, Maharashtra, India. IIT Bombay was founded in 1958. In 1961, the Parliament decreed IITs as Institutes of National Importance.\r\n', '', '', ''),
(66, '2022-12-12 07:03:37', 'Institute of chemical technology', 'MUMBAI', 'MUMBAI', 'MUMBAI', 'B.TECH,M.TECH,B.PHARMA,M.PHARMA,BSC', 'VA11\r\nVA12\r\nVA8\r\nVA17\r\nVA29', 1933, 'UGC, NBA, MHRD', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/ICTMUMBAI.jpg', 'Established on October 1, 1933 as University Department of Chemical Technology (popularly called UDCT) of the University of Bombay (now Mumbai), with the noble intention of advancing India\'s knowledge reserves in chemical science and technology, the Institute has grown to become a premier (deemed) university devoted to education, training, research and industrial collaboration in chemical engineering, chemical technology, applied chemistry, pharmacy, biotechnology and bio-processing.\r\n\r\n\r\n\r\n', '', '', ''),
(67, '2022-12-12 07:06:04', 'Veermata jijabai technological institute', 'MUMBAI', 'MUMBAI', 'MUMBAI', 'MCA,M.TECH,B.TECH,PHD', 'VA7\r\nVA12\r\nVA11\r\nVA34', 1887, 'AICTE', 'UG, PG', 'NA', 'NA', 'http://vidyarthiadda.com/images/VIRMATA.jpg', 'Veermata Jijabai Technological Institute is a state funded college located in Mumbai, Maharashtra, India, and one of the oldest engineering colleges in Asia. Founded in 1887 and formerly known as the Victoria Jubilee Technical Institute, it adopted its present name on 26 January 1997.\r\n\r\n\r\n', '', '', ''),
(68, '2022-12-12 07:07:54', 'KJ somaiya institute of engineering and information technology', 'MUMBAI', 'MUMBAI', 'MUMBAI', 'B.TECH,M.TECH', 'VA11\r\nVA12', 2001, 'AICTE', 'UG, PG', '13 LPA', '7 LPA', 'http://vidyarthiadda.com/images/KJSOMAYA.jpg', 'his second Engineering College established by the Somaiya Trust in the year 2001, at Ayurvihar campus, Sion, was initiated with a first batch of 180 undergraduate students and three branches in Engineering—namely Electronics and Telecommunication Engineering, Computer Engineering, and Information Technology.\r\n', '', '', ''),
(69, '2022-12-14 12:11:07', ' Accman business school greater Noida\r\n', 'UTTAR PRADESH \r\n', 'greater Noida\r\n', 'Greater Noida\r\n', 'BBA,B.COM,MBA', 'VA4\r\nVA5\r\nVA1\r\n', 2003, 'AICTE', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', '\r\nhttp://vidyarthiadda.com/images/ACCMAN.jpg', 'ACCMAN Business School, Greater Noida is functioning under the aegis of Balibhadra Foundation, a registered trust established in year 2003 by practicing professional who are working with the mission to provide academically relevant, and industry focused quality education at affordable cost. Marked their presence in technical education by establishing ACCMAN Institute of Management in year 2006. In short span of time it has made significance contribution in the area of management education.\r\n\r\n\r\n', '', '', ''),
(70, '2022-12-14 12:20:50', 'Apeejay institute of technology greater noida\r\n', 'UTTAR PRADESH', 'greater noida', 'Greater Noida', 'B.Tech', 'VA11', 1999, 'AICTE,COA', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/APEEJAY.jpg', '\"The campus, about 2 kms. from Pari Chowk on Noida-Greater Noida expressway, is a part of the Institutional Area of Greater Noida - a modern, well planned and fast growing city. It shall offer the students a lifetime opportunity to witness the growth and development of a new settlement, enabling pragmatic visions on architectural ideas, urban design and landscape design. It is well connected to Noida, Delhi and other surrounding areas by road network. Regular frequent bus service is available from N. Delhi/Noida to Apeejay Campus, Greater Noida.\r\n\r\nThe School of Architecture & Planning is an integral constituent of the Apeejay Institute of Technology situated in Greater Noida, Dist. Gautam Budh Nagar, U.P. India. The Apeejay campus occupies an area of 29.0 acres with additionally a School of Management, School of Computer Sciences and an International School already functioning. The campus also has residential facility for the students and the faculty members, thus fostering a healthy interface for learning. Campus is enabled with Wi-fi facilities.\"\r\n', '', '', ''),
(71, '2022-12-14 12:27:20', 'Army institute of management and technology greater Noida\r\n', 'UTTAR PRADESH', 'greater noida', 'Greater Noida', 'BBA,MBA', 'VA4\r\nVA1\r\n', 2004, 'AICTE', 'UG,PG', '10 Lac', '5 Lac', 'http://vidyarthiadda.com/images/ARMY.jpg', 'Army Institute Of Management & Technology (AIMT) is a premium MBA Institute in Greater Noida (NCR) near Delhi. Established by the Army Welfare Education Society (AWES) in 2004 in the hi-tech city of Greater Noida. The forerunner of the Institute was Faculty of Management Studies (FOMS), College of Materials Management (CMM), Jabalpur which was set up in summers of 1995. In a span of about ten years, FOMS carved a niche for itself and became a reputed business institution. In 2002 the college relocated and re-established itself with a new identity and a new name in the plush and quite environs of Greater Noida (NCR).\r\n\r\n', '', '', ''),
(72, '2022-12-14 13:55:19', 'BBS institute of management studies greater Noida\r\n', 'UTTAR PRADESH', 'greater noida', 'Greater Noida', 'MCA\r\nMBA', 'VA7\r\nVA1', 2006, 'AICTE', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/BBS.jpg', '\"BBS Institute was established under BENI MADHAV SHIKSHA SAMITI in 2002, affiliated to Dr. A.P.J Abdul Kalam Technical University and approved by AICTE, MHRD Govt. of India (New Delhi)\r\n\r\nThe college is spread over the vast area of 27 acres of land with around 15000 sq. meters of build-up area. It has a well-furnished & maintained hostel facility for boys and girls separately.\r\n\r\nIn this competitive era where the world is focused on ‘quantity’, we focus on ‘quality’. We know the worth of the word ‘passion’ and ‘commitment’. And focussing on all these we make sure that we build a strong foundation in carving the best in our students.\"\r\n\r\n', '', '', ''),
(73, '2022-12-14 13:58:58', 'Bakson Homoeopathic medical College and hospital greater Noida\r\n', 'UTTAR PRADESH \r\n', 'greater Noida\r\n', 'Greater Noida\r\n', 'MD,BHMS', 'VA41\r\nVA42', 2002, ' DBRAU Agra\r\n', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/BAKSON.jpg', '\"Homoeopathic education in India witnessed phenomenal change during his tenure, under his able guidance. He was not only instrumental in rationalising homoeopathic education in India but also introduced the concepts of quality and accountability in homoeopathic practice by initiating amendments to the Homoeopathic Practitioners (Professional Etiquettes, Conduct and Code of Ethics) Regulations.\r\n\r\nDr. Bakshi is the founder Chairman of Bakson Drugs & Pharmaceuticals Pvt. Ltd., a leading homoeopathic drug manufacturing and marketing company. Dr. Bakshi has also to his credit the establishment of a nationwide chain of Bakson\'s Homoeopathy Clinics known for treating various disorders, including Allergy. He has treated more than a million patients over his 38 years of long professional career.\"\r\n\r\n', '', '', ''),
(74, '2022-12-14 14:03:06', 'Dronacharya group of institutions greater Noida\r\n', 'UTTAR PRADESH \r\n', 'greater noida', 'Greater Noida', 'B.Tech\r\nMBA', 'VA11\r\nVA1', 2006, 'AICTE', 'UG,PG', '45 LAC', '18 LAC', 'http://vidyarthiadda.com/images/DRONACHARYA.jpg', 'To impart Quality Education, to give an enviable growth to seekers of learning, to groom them as World Class Engineers and Managers competent to match the expanding expectations of the Corporate World has been ever enlarging vision extending to new horizons of Dronacharya Group of Institutions\r\n\r\n', '', '', ''),
(75, '2022-12-14 14:11:02', 'IEC group of institutions greater Noida\r\n', 'UTTAR PRADESH', 'greater noida', 'Greater Noida', 'B.Tech, MBA, M.Tech, M.Pharma', 'VA11\r\nVA1\r\nVA12\r\nVA17\r\n\r\n', 1999, 'AICTE', 'UG,PG', '10 LAC', '4.6 LAC', 'http://vidyarthiadda.com/images/IEC.jpg', '\"IEC Group, found its genesis way back in the year 1981 when Sh. R.L. Gupta, laid the stone to found India Education Centre under his aegis with a dream to make India leader in Information Technology .Soon it become the frontrunner in imparting IT Education. In year 1994 with aim of expansion it was corporatized and India Education Centre Ltd. was founded later named IEC Softwares Ltd. and now IEC Education Ltd. (ISO:9001)\r\n\r\nIEC with a market capitalization of over 50 crore rupees one of the pioneers in India, in the field of Information Technology has been a frontrunner in imparting IT training and Education at the length and breadth of the Country. IEC Education Limited is Listed on Bombay, Delhi, Greater Noida Stock Exchanges.\"\r\n\r\n\r\n\r\n', '', '', ''),
(76, '2022-12-14 14:14:53', 'ITS engineering college greater Noida.\r\n', 'UTTAR PRADESH', 'greater noida', 'Greater Noida', 'B.Tech, MBA', 'VA11\r\nVA1', 2006, 'AICTE, NBA', 'UG\r\nPG', '29.5 LAC', '3.5 LAC', 'http://vidyarthiadda.com/images/ITS.jpg', 'ITS Engineering College keeps in mind the ever changing technical skills requirement for industries in India and abroad. Our teaching methods are designed to ensure technology based learning which is in addition to the domain knowledge of the chosen engineering branch. Students get hands on experience through internships in core companies in their chosen branches, experiential learning through industry visits, live projects, expert talks, MOOCs, workshops, case studies, upscale labs, and virtual classroom sessions. Our faculty members keep themselves abreast with the current industry developments and make substantial contribution to the academia through quality teaching, patent publications, seminars and conferences etc. Our constant efforts have made us the top engineering college in Greater Noida and one of the best engineering colleges in AKTU.\r\n\r\n', '', '', ''),
(77, '2022-12-14 14:24:35', 'Gautam Buddha University greater Noida\r\n', 'UTTAR PRADESH', 'greater noida', 'Greater Noida', 'BBA\r\nMBA\r\nB.TECH\r\nB.ED\r\nB.COM\r\nBCA\r\nBA\r\nLAW\r\n', 'VA4\r\nVA1\r\nVA11\r\nVA14\r\nVA5\r\nVA6\r\nVA27\r\nVA10\r\n', 2008, 'NCTE \r\nCOA \r\nBCI \r\nUGC\r\n', 'UG,PG', '11 LAC', '3 LAC', 'http://vidyarthiadda.com/images/GAUTAM.jpg', 'Gautam Buddha University (\"GBU\") (HINDI) is a university established by the Uttar Pradesh Gautam Buddha University Act 2002 (UP Act No. 9 of 2002) and came into existence in 2008. It is approved by University Grants Commission (UGC) under section 12-B and accredited by National Assessment and Accreditation Council (NAAC) with B+ grade. It is located in Greater Noida, Gautam Buddha Nagar in Uttar Pradesh, India.[2][3] It is one of Uttar Pradesh\'s state government universities which commenced its first academic session in the year 2008. University campus is spread over 511 acres (207 ha) in greater Noida and offers Bachelors, Masters and Doctoral degrees in Engineering, Business Administration, Computer Applications, Biotechnology and Buddhist Studies and is mainly focused on research.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n', '', '', ''),
(78, '2022-12-14 14:30:59', 'JSS academy of technical education Noida.\r\n', 'UTTAR PRADESH \r\n', 'Noida', 'Noida', 'MCA\r\nMBA\r\nB.Tech\r\nM.Tech', 'VA7\r\nVA1\r\nVA11\r\nVA12\r\n', 1998, 'NICTE\r\nPCI', 'UG\r\nPG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/JSS.jpg', 'JSS Academy of Technical Education Noida (JSSATEN) is one of the leading Technical Institutions in the National Capital Region in the State of Uttar Pradesh. Established in the year 1998 by JSS Mahavidyapeetha, Noida, the Institution has set bench marks every year, and grown into an Institution of Excellence in Technical Education. Located in the central part of NOIDA, JSSATEN has become a household name for its excellence in Discipline, Teaching, Training and Placement. Today, JSSATEN has total student strength of over 4000, who are mentored by more than 250 Faculty Members. The Campus has finest accommodation for girls and boys.\r\n\r\n\r\n\r\n', '', '', ''),
(79, '2022-12-14 18:30:30', 'Amity law school. New delhi', 'DELHI', 'new delhi', 'new delhi', 'LLM\r\nLLB\r\nBA.LLB\r\nBBA.LLB\r\nB.COM LLB', 'VA33\r\nVA44\r\nVA45\r\nVA46\r\nVA47', 1995, 'BCI,\r\nAICTE,\r\nCOA', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/AMITY.jpg', '\"The Amity Law School, Delhi has been consistently ranked as one of the Top Law Schools in the country since 2006. In the survey of the India’s Best Law Colleges in 2015, the school has been ranked No. 11 by THE WEEK- HANSA RESEARCH SURVEY, No. 13 by INDIA TODAY- NIELSEN SURVEY, and No. 13 by THE OUTLOOK-G/K MODE SURVEY.\r\n \r\n The Law School has the unique distinction of being the first Law School in Delhi to start a 5-year integrated LL.B (H) programme. The School was established under the Ritnand Balved Education Foundation (RBEF) to achieve world-class legal education in the country. Dr. Ashok K. Chauhan, the Founder President of the Law School is a great philanthropist and a man of extraordinary vision. This vision of his has been translated into practical reality through the establishment of various educational institutions he has set up including the Amity Law School. His vision for the Law School is to provide excellence in legal education and to produce quality lawyers with good moral principles and great human values.\"\r\n\r\n\r\n\r\n', '', '', ''),
(80, '2022-12-14 18:33:54', 'Delhi metropolitan education. Noida', 'UTTAR PRADESH', 'Noida', 'Noida', 'BBA\r\nBA.LLB\r\nBA', 'VA4\r\nVA45\r\nVA27', 2012, 'BCI', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/DELHI.jpg', '\"Delhi Metropolitan Education (DME) was established on 1st August, 2012, under the aegis of Sunshine Educational & Development Society which has been working dedicatedly in the field of education for over 16 years. DME is affiliated to the prestigious Guru Gobind Singh Indraprastha University (GGSIPU), New Delhi and is approved by the Bar Council of India.\r\n \r\n DME envisions creating future leaders and nation builders by its endeavours in educating young minds. The institute is committed towards forming and sustaining conditions enabling students to embark on an unparalleled educational journey that is intellectually, socially, and personally transformative and enriching. DME offers sought after courses in the field of Management, Journalism and Law as given below:\"\r\n\r\n', '', '', ''),
(81, '2022-12-14 18:37:53', 'Symbiosis law school. Noida.', 'UTTAR PRADESH', 'Noida', 'Noida', 'LLM\r\nBA.LLB\r\nBBA.LLB', 'VA33\r\nVA45\r\nVA46', 2010, 'BCA,\r\nNAAC', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/SYMBIOSISNOIDA.jpg', 'Symbiosis Law School, NOIDA (hereinafter referred to as SLS-NOIDA) in just the tenth year of its inception has carved a niche for itself in the academic circuits. It has become a celebrated name amongst the aspirants of professional legal education. It holistically promotes academic excellence, intellectual discipline and professional leadership. Being a constituent of Symbiosis International (Deemed University), it envisions the reputation of Symbiosis in and around Delhi - the constitutional capital of India. SLS-NOIDA is strategically located in the industrial hub of NCR, thereby opening up a plethora of opportunities for budding lawyers.\r\n\r\n', '', '', ''),
(82, '2022-12-14 18:42:43', 'Mahatma Gandhi mission College of engineering and technology. Noida', 'UTTAR PRADESH', 'Noida', 'Noida', 'B.Tech', 'VA11', 1999, 'AICTE', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/MAHATMA.jpg', '\"Engineering is not just about a few mandatory courses and elective programs, it is a process intended to bring about transformation in your perspective and is about giving you new thoughts, new visions and new ambitions with scientific approach. With Liberalization and Globalization, the India corporate sectors felt the need to reposition itself, quickly in order to effectively respond to emerging competition and also exploit the opportunities.\r\n The new challenges will not be surmounted with yesterday\'s concepts and the day before yesterday\'s strategies and technologies but rather with our ability and thinking futuristic and redefining our action plan for today.\r\n To cater to this requirement, we aim to live up to our mission to groom young future engineers to be complete, value driven human beings and competent professionals with global outlook and capable of functioning in cross functional teams, to balance scientific principles with practical applications in Engineering design.\"', '', '', ''),
(83, '2022-12-14 18:52:55', 'Apeejay svran international college. Noida', 'UTTAR PRADESH', 'Noida ', 'Noida', 'MBA', 'VA1', 1967, 'AICTE,\r\nAIU', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/APEEJAY.jpg', '\"Apeejay Svran International College (ASIC) under the aegis of Apeejay Education Society in collaboration with the School of Business , University of Greenwich , U.K offers the MBA International Business programme. The Partnership between University of Greenwich in the UK and Apeejay Svran International College , Greater Noida brings you this dynamic programme that will add a new dimension to your professional career Ã¢ï¿½ï¿½ one that combines international managerial practices with an Indian ethos and values.\r\n \r\n Apeejay Svran International College (ASIC) campus at Greater Noida, is an integral part of Apeejay Education Society and is managed by well-known experts and an empowered management board. ASIC is committed to imparting quality education to aspiring students by offering them a wide range of professional programmes. Practical experience on advanced analytical software like SAP, SPSS, Sugar CRM and Oracle is imparted through alliances and partnerships. The campus also enhouses School of Management which has created a land mark by providing quality education in the field of management.\"', '', '', ''),
(84, '2022-12-14 18:58:13', 'Rajiv gandhi institute of petroleum technology. Noida', 'UTTAR PRADESH', 'Noida', 'Noida', 'B.Tech\r\nM.Tech\r\nMBA', 'VA11\r\nVA12\r\nVA1', 2007, 'NOT FOUND', 'UG,PG', '18 LAC', '10 LAC', 'http://vidyarthiadda.com/images/RAJIV.jpg', 'The Ministry of Petroleum & Natural Gas (MOP&NG), Government of India set up The Rajiv Gandhi Institute of Petroleum Technology (RGIPT) at Jais, Dist. Amethi, Uttar Pradesh through an Act of Parliament (“Rajiv Gandhi Institute of Petroleum Technology Act 2007\"). RGIPT has been accorded the eminence of being an “ Institute of National Importance” along the lines of the Indian Institutes of Technology (IIT). The Institute is empowered to award degrees in its own right. RGIPT is co-promoted as an energy domain specific institute by six leading Oil Public Sector Units (ONGC, IOCL, OIL, GAIL, BPCL and HPCL) in association with the Oil Industry Development Board (OIDB) [ This however does not bind them to preferentially recruit from RGIPT ]. The Institute is associating with leading International Universities/Institutions specializing in the domain of Petroleum Technology.\r\n\r\n', '', '', ''),
(85, '2022-12-14 19:09:09', 'NIILM centre for management studies. Greater noida', 'UTTAR PRADESH', 'Greater Noida', 'greater noida', 'MBA\r\nPGDM', 'vA1\r\nVA3', 1996, 'AICTE', 'UGM', '7 LAC\r\n8 LAC', '4.7 LAC', 'http://vidyarthiadda.com/images/NIILM.jpg', 'NIILM Centre for Management Studies is situated in Greater Noida in Uttar Pradesh state of India. Established in 1996, NIILMCMS is a Private college. The college is accredited by AIU, UGC, NBA, AICTE. NIILM Centre for Management Studies offers 9 courses across 1 streams namely Management. Popular degrees offered at NIILM Centre for Management Studies include PGDM. Besides a robust teaching pedagogy, NIILM Centre for Management Studies is also a leader in research and innovation. Focus is given to activities beyond academics at NIILM Centre for Management Studies, which is evident from its infrastructure, extracurricular activities and national & international collaborations. The placement at NIILM Centre for Management Studies is varied, with recruitment options both in corporates and public sector as well as entrepreneurship.\r\n', '', '', ''),
(86, '2022-12-14 19:13:21', 'Maharishi institute of management. Noida', 'UTTAR PRADESH', 'Noida', 'Noida', 'MBA,\r\nPGDM', 'VA1\r\nVA3', 1995, 'AICTE', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/MAHARISHI.jpg', 'Maharishi Institute of Management (MIM) is a group of private institutes founded by Maharishi Mahesh Yogi[3] with locations in Maharishi Nagar(NOIDA),[4] Bhopal, Indore, Hyderabad, Bengaluru and Chennai, India.[5] The Institute is accredited by the All India Council for Technical Education (AICTE) and offers Graduate and Post Graduate courses in Management and Computer Science.[6] Maharishi Institute of Management[7] is a part of Maharishi Mahesh Yogi\'s global education movement. MIM is established under the auspices of Maharishi Shiksha Sansthan (MSS).\r\n', '', '', ''),
(87, '2022-12-14 19:18:24', 'Vallabhbhai Patel chest institute new delhi', 'DELHI', 'new delhi', 'new delhi', 'PHD\r\nDM\r\nMD', 'VA34\r\nVA48\r\nVA41', 1953, 'PUBLIC,\r\nDU', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE\r\n', 'http://vidyarthiadda.com/images/VALLABHAI.jpg', 'Vallabhbhai Patel Chest Institute is a postgraduate medical institute located in New Delhi, India, and supported by the University of Delhi. The Ministry of Health & Family Welfare of India takes care of its endowment. It has been categorized as one of the constituent colleges of the University of Delhi.\r\n\r\n', '', '', ''),
(88, '2022-12-14 19:29:42', 'Sri venkateshwara college. Delhi', 'DELHI', 'new delhi', 'new delhi', 'BA\r\nB.SC\r\nB.COM\r\nM.SC\r\nMA', 'VA27\r\nVA29\r\nVA5\r\nVA30\r\nVA28', 1961, 'NAAC', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/VENKATESWARA.jpg', 'Sri Venkateswara College is a constituent college of the University of Delhi established in 1961 in New Delhi, India. It is managed by Tirumala Tirupati Devasthanams & UGC and awards degrees under the purview of the University of Delhi\r\n\r\n\r\n\r\n', '', '', ''),
(89, '2022-12-14 19:33:05', 'Sri Aurobindo college New delhi', 'DELHI', 'new delhi', 'new delhi', 'BA\r\nB.SC\r\nB.COM', 'VA27\r\nVA29\r\nVA5', 1972, 'NAAC', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/AUROBINDO.jpg', 'Sri Aurobindo College is a constituent college of the University of Delhi in India. It was established in year 1972, which was the birth centenary year of the philosopher, patriot-poet, Sri Aurobindo. The college is situated in South Delhi in Malviya Nagar, in the vicinity of Qutab Minar, Sri Aurobindo Ashram, IIT (Delhi), NCERT and Qutab Institutional Area.[1]\r\n\r\n', '', '', ''),
(90, '2022-12-14 19:37:54', 'Sri guru gobind singh college of commerce delhi', 'DELHI', 'new delhi', 'new delhi', 'BA\r\nBSC\r\nB.COM\r\nMA\r\nMSC', 'VA27\r\nVA29\r\nVA5\r\nVA28\r\nVA30', 1961, 'PUBLIC DU', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/GURUGOBIND.jpg', 'Sri Guru Gobind Singh College of Commerce, often referred to by its initials SGGSCC, is a constituent college of the University of Delhi located in Delhi, India. It was founded in 1984 and is named after the tenth Sikh Guru.\r\n\r\n\r\n\r\n', '', '', ''),
(92, '2022-12-19 12:52:51', 'Shyam lal college New delhi.\r\n', 'DELHI', 'new delhi', 'new delhi', 'BA\r\nBSC\r\nB.COM\r\nMA', 'VA27\r\nVA29\r\nVA5\r\nVA28', 1964, 'UGC\r\nNAAC', 'UG\r\nPG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/SHYAMLAL.jpg', '\"Shyam Lal College is recognised as a co-educational constituent college of Delhi University . It offers 11 undergraduate courses in the fields of Science, Commerce and Humanities and 1 postgraduate course in Hindi to more than 3940 students. Admission to UG courses is based on the Common University Entrance Test (CUET) followed by e-counseling. Candidates seeking admission to PG courses are required to appear for the Delhi University Entrance Test (DUET). \r\n\r\nPadmashree (Late) Shri Shyam Lal Gupta founded Shyam Lal College in 1964 and the college is affiliated with the University of Delhi. SLC focused on imparting quality education to students, particularly to the girls belonging from East Delhi’s underprivileged communities. It provides special Remedial and Spoken English classes on a regular basis for students who find it difficult to keep pace with the curriculum.\"\r\n\r\n\r\n\r\n', '', '', ''),
(93, '2022-12-19 17:31:25', 'Satyavati college New Delhi', 'DELHI', 'new delhi', 'new delhi', 'BA\r\nBSC\r\nB.COM\r\nMA', 'VA27\r\nVA29\r\nVA5\r\nVA28', 1972, 'UGC\r\nNAAC', 'UG\r\nPG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/SATYAWATI.jpg', '\"Satyawati college is a co-educational constituent college of University of Delhi. The college offers several UG courses in different specializations. It also has a single PG course offered under the faculty of Arts and specialization in Political Science. Besides academic excellence, the college is also known for its achievements in extracurricular activities. The Sports Department of the college conducts 20 different sports activities in a year. Admission to UG courses is based on the Common University Entrance Test (CUET) followed by e-counseling. Candidates seeking admission to PG courses are required to appear for the Delhi University Entrance Test (DUET). \r\n\r\nThe Delhi Government established Satyawati College in 1972 and is one of the off campus colleges of the University of Delhi. At present the college has 10 Departments and numerous courses. The college has been accredited by NAAC with Grade A and affiliated to Delhi University. The college has a diversified environment with students coming from different backgrounds in terms of culture, religion and socio-economic status\"\r\n\r\n\r\n', '', '', ''),
(94, '2022-12-19 17:39:55', 'Holy family college of nursing. New delhi', 'DELHI', 'new delhi', 'new delhi', 'DIPLOMA\r\nBSC\r\nMSC\r\nGNM', 'VA37\r\nVA29\r\nVA30\r\nVA48', 1956, 'INC', 'UG\r\nPG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/HOLYFAMILY.jpg', '\"The school of Nursing, Holy family Hospital, New Delhi started in 1956, which later became the College of Nursing. Its mission is to assist students to become competent professional nurses in the promotion of health, prevention of disease, care during illness, and rehabilitation of the clients. \r\n\r\nIt offers Undergraduate and Postgraduate courses in the field of  Paramedical and Medical. The admission criteria are based on the merit of the selection test.\"\r\n\r\n\r\n', '', '', ''),
(95, '2022-12-20 08:50:00', 'Indian institute of technology (IIT) delhi', 'DELHI', 'new delhi', 'new delhi', 'B.Tech\r\nM.tech\r\nMSC\r\nMBA', 'VA11\r\nVA12\r\nVA30\r\nVA1', 1961, 'AICTE', 'UG,PG', '4 CPA', '1 CPA', 'http://vidyarthiadda.com/images/IITDELHI.jpg', '\"Indian Institute of Technology Delhi, popularly known as IIT Delhi, is a public research and engineering institute, established in 1961. The institute has its main campus located at Hauz Khas in Delhi, India. In addition, it has two extension campuses, one in Sonepat, and one in Jhajjar. It is one of the oldest IITs in India and has been declared as an “Institute of Eminence” by the government of India. \r\n\r\nIIT Delhi is best known for its wide variety of engineering programs and outstanding placement records. The college has been consistently ranked #2 among the top engineering colleges in India. For the flagship B.Tech program, the institute has always been one of the top preferences among all IITs. The institute charges an annual fee of INR 8.3 Lakhs for the same. Candidates who have cleared JEE Advanced examination and have secured an all India rank (AIR) of 1-100 are more likely to get admission to the IIT Delhi B.Tech program.\r\n\r\nApart from the flagship program, IIT Delhi offers more than 100 courses under UG, PG, Dual, and Doctoral degrees. Additionally, the institute offers online certificate programs in the fields of Digital Marketing, Product Development, and Management. Check IIT Delhi Courses & Fees\r\n\r\nIIT Delhi conducted its Phase 1 placements for the batch 2023 on December 1, 2022 and Jane Street offered the Highest Package of INR 4 CPA. Check IIT Delhi Placements\"\r\n\r\n\r\n', '', '', ''),
(96, '2022-12-20 08:55:16', 'Jamia millia islamia (JMI) New delhi', 'DELHI\r\n', 'new delhi', 'new delhi', 'MBA\r\nBBA\r\nB.TECH\r\nB.ED\r\nB.P.T\r\nMCA\r\nMA', 'VA1\r\nVA4\r\nVA11\r\nVA14\r\nVA49\r\nVA7\r\nVA28', 1920, 'AICTE\r\nUGC', 'UG,PG', '25 LAC', '9 LAC', 'http://vidyarthiadda.com/images/JAMIAMILIA.jpg', '\"Jamia Millia Islamia (JMI) is a central university located in New Delhi. JMI is ranked 3rd among the top universities in India by NIRF 2022. Jamia offers UG, PG, and Doctoral programs in the fields of Arts, Science, Commerce, Hospitality, Technology, Management, Architecture, Education, and Polytechnic. Admission to all the courses except the B.Tech program is based on marks obtained in the entrance exam conducted by the university itself. Admission to the B.Tech program is based on JEE Main exam scores. Applications for admission are accepted in online mode along with the required application fee and documents. Jamia Millia Islamia has been ranked 195 by the Times Higher Education Emerging Economies University Rankings 2021. The university is also ranked in the band of 751-800 by the QS World Ranking 2022.\r\n\r\nThe institute concluded its 2022 MBA placement drive that engaged more than 25 recruiters. Students received an average salary of INR 9 LPA. The highest salary package stood at INR 25 LPA. The notable alumni of Jamia Millia Islamia include Shah Rukh Khan, Virender Sehwag, Neha Bisht, Kiran Rao, Mouni Roy, and Barkha Dutt.\"\r\n\r\n\r\n\r\n\r\n\r\n', '', '', ''),
(97, '2022-12-20 09:07:15', 'Faculty of nursing. Jamia hamdard new delhi.', 'DELHI', 'new delhi', 'new delhi', 'BSC\r\nNURSING', 'S12345\r\nYU6789', 1983, 'AICTE\r\nUGC', 'UG\r\nPG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/FACULTY.jpg', 'The history of Jamia Hamdard begins with the establishment of a small Unani clinic in the year 1906 by Hakeem Hafiz Abdul Majeed, one of the well-known practitioners of Unani System of Medicine of his time. Hakeem Hafiz Abdul Majeed had a vision of making the practice of Unani Medicine into a scientific discipline so that Unani medicines could be dispensed in a more efficacious manner to patients. He gave the name “Hamdard” to his venture which means “sympathy for all and sharing of pain”. His illustrious son, Hakeem Abdul Hameed, carried forward the philosophy and objectives of Hamdard in independent India. Even at the time of partition of India in 1947, Hakeem Abdul Hameed was dreaming of setting up a complex of educational institutions which would concentrate on highlighting the contribution of Islam and Islamic culture to Indian civilization and development of Unani medicines for curing diseases\r\n', '', '', ''),
(98, '2022-12-20 09:10:38', 'Fairfield institute of management and technology new delhi', 'DELHI', 'new delhi', 'new delhi', 'BBA\r\nBCA\r\nBA.LLB\r\nB.COM', 'VA4\r\nVA6\r\nVA45\r\nVA5', 2009, 'IPU', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/FAREFIELD.jpg', 'Fairfield Institute of Management and Technology, New Delhi is shortly known as FIMT was established in the year 2009 by the Fairfield Group of Institutions. Fairfield Institute of Management and Technology is affiliated with Guru Gobind Singh Indraprastha University (GGSIPU). It is also accredited by the Department of Higher Education (DHE) and is the Government of NCT Delhi approved as well. The institute has 9 different undergraduate courses across different domains such as Art, Law, Commerce and Management. FIMT also offers integrated, general and honors programs in a diverse range of courses. All admissions are done based on the marks obtained in the previous qualifying exams. Students applying for courses under Law are required to write CLAT (Common Law Admission Test). The top recruiters of FIMT are Godrej, Hero Honda, HP, and ICICI Bank.\r\n\r\n\r\n', '', '', ''),
(99, '2022-12-20 09:14:22', 'Maulana Azad institute of dental sciences new delhi', 'DELHI', 'new delhi', 'new delhi', 'BDS\r\nMDS', 'VA15\r\nVA16', 1983, 'DCI', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/MAULANA.jpg', '\"Located in the heart of National Capital Territory of Delhi, Maulana Azad Institute of Dental Sciences enjoys the best of what Old and New Delhi has to offer. Surrounded by Chandni Chowk, Daryaganj, Connaught Place and the Ferozshah Kotla, it is at the hub of cultural, entertainment and intellectual activities. MAIDS is situated in a spacious campus alongside the city\'s four prestigious landmark hospitals namely, Maulana Azad Medical College, Lok Nayak Hospital, G. B Pant and Guru Nanak Eye Centre.\r\n\r\nThe first mention of Lok Nayak Hospital (formerly Irwin hospital) can be traced to 10th January 1930 when Lord Irwin laid down the foundation stone of the hospital. Indian Medical Service at that time was heavily manned by the British. In 1940, Col. Curickshank of the Indian Medical Service (IMS), a British national, was appointed Medical Superintendent of Irwin Hospital and Chief Medical Officer of New Delhi. The medical and dental institute derived its name from Maulana Abul Kalam Azad who was the first Union Minister of education and scientific research of independent India.\"\r\n', '', '', ''),
(100, '2022-12-20 09:17:16', 'Dr Bhim Rao Ambedkar college New delhi', 'DELHI', 'new delhi', 'new delhi', 'BA\r\nB.COM', 'VA27\r\nVA5', 1991, 'NAAC', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/DRAMBEDKAR.jpg', 'Dr Bhim Rao Ambedkar College BRAC came into existence on 8th Feb 1991 during the birth centenary year of Bharat Ratna Baba Saheb Dr Bhim Rao Ambedkar with Dr PC Patanjali as the founder Principal. It is a constituent co-educational college of the University of Delhi and is 100 % funded by Delhi Government. Since its inception, it has maintained its incessant momentum on the path of progress, both in academics and extra-curricular fields. The Principal, teaching & non-teaching Staff have dedicated themselves to build an environment of holistic and inclusive learning, inspiring the youth to create a fruitful and responsible future. The college completed its Silver Jubilee 25th year of operation in 2016 and the year was celebrated with a number of academic events, workshops and conferences. The college has a unique combination of academic and professional courses under the three year Bachelor Degree Programmes. The prominent academic programmes include BCom & BCom Hons, BA Hons Geography, BA Hons History and the evergreen BA Programme. The college holds the unique distinction of being the forerunner in launching four professional courses of the University namely BA Hons Hindi Journalism and Mass Communication which was introduced in 1994-95, BA Hons Social Work and BA Hons Business Economics which were started in 1995-96 and BA Hons Applied Psychology which was introduced in 2007- 08. The college has a distinction of offering some Commerce based courses like Human Resource Management HRM and Office Management and Secretarial Practice OMSP besides the Vocational Course like Functional Hindi FH to the students of BA Programme. The college is privileged to have WUS Health Centre in its premises to look after the health care needs of students of Delhi University and its employees. The College is situated near upcoming Metro station which will soon be operational. Under the capacity expansion plan initiated by GNCTD, the University has selected our college as one of the Regional-cum-Study Centres to facilitate undergraduate teaching under Personal Contact Programme PCP for School of Open Learning SOL students. The college is also one of the Centres for teaching to the girl students under Non Collegiate Women Education Board NCWEB, University of Delhi. Our College has also been selected as one of the 12 Centres spread all over India by Rajiv Gandhi National Institute of Youth Development, Ministry of Youth Affairs & Sports, Tamil Nadu which offers one year Post Graduate Diploma in Youth Development PGDYD under the coordinatorship of Dr SS Chawla.\r\n', '', '', ''),
(101, '2022-12-20 09:20:04', 'Maharishi Valmiki college of education new delhi', 'DELHI', 'new delhi', 'new delhi', 'B.ED', 'VA14', 1995, 'NCTE', 'UG,PG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/MAHARISHIVALMIKI.jpg', '\"Maharshi Valmiki College of Education was established in the year 1995 by the Govt of NCT of Delhi as a Constituent College of University of Delhi to cater to the long standing need for providing avenues for pre-service elementary and secondary teacher education programmes for the aspiring students in Delhi. Initially known as College of Education and housed on the Ground Floor of Bhai Parmanand Institute of Business Studies Building, Shakarpur, Delhi the college assumed its present name, Maharshi Valmiki College of Education, later in the year 1997 drawing inspiration from the high ideals of the great teacher Valmiki.\r\n\r\n\r\nMarking a humble beginning with its Bachelor of Education programme with only 38 students from the Humanities and Social Science streams, the college got initiated into the process of shaping its promising profile under the inspirational leadership of the philosopher, artist and teacher late Professor RP Sharma, Former Head & Dean, Faculty of Education, University of Delhi, who took over as its Founder Principal Officer on Special Duty on 21 September 1995, the day since being celebrated as Udbhav Diwas every year. The college was formally inaugurated by Sh Madan Lal Khurana, the then Chief Minister of Delhi on 16 November 1995, the day since being celebrated as the Foundation Day every year. The college moved to its present location in Geeta Colony in the year 2003. The admissions to the B Ed course of the college are made through a Common Entrance Test conducted by the Faculty of Education, University of Delhi.\"', '', '', ''),
(102, '2022-12-20 09:29:37', 'International college of financial planning (ICoPF) new delhi', 'DELHI', 'new delhi', 'new delhi', 'MBA\r\nDIPLOMA', 'VA1\r\nVA37', 2002, 'NAAC', 'UG\r\nPG', '6.5 LAC', '4 LAC', 'http://vidyarthiadda.com/images/IIF.jpg', 'International College of Financial Planning (ICoFP), established in 2002 is an educational initiative of the Bajaj Capital Group. With 7+ awards and accolades, it is one of the leading providers of education on Wealth Management. ICoFP offers various industry-oriented and award-winning full-time programs which integrate the curriculum of some of the most acclaimed professional certifications globally. The flagship program of ICoFP is Integrated Diploma in Wealth Management. For admission to the Integrated Diploma course, a valid postgraduation degree is required\r\n', '', '', ''),
(103, '2022-12-20 09:33:23', 'School of aeronautics new delhi', 'DELHI', 'new delhi', 'new delhi', 'B.TECH', 'VA11', 1992, 'AICTE', 'UG\r\nPG', 'PACKAGE NOT DISCLOSE', 'PACKAGE NOT DISCLOSE', 'http://vidyarthiadda.com/images/AERONAUTICS.jpg', '\"School of Aeronautics established in 1992, since then we are into providing world class Aviation Education, in various disciplines. School of Aeronautics Neemrana established in 2006, after successfully running School of Aeronautics Delhi for 14 years.\r\n\r\nThe managing body is Laxmi Narain Verma Memorial Society, is founded in the loving memory of Shri LN Verma and registered under Societies registration Act XXI of 1860, registered at New Delhi.\"', '', '', '');

-- --------------------------------------------------------

--
-- Table structure for table `entries`
--

CREATE TABLE `entries` (
  `id` int NOT NULL,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` varchar(400) NOT NULL,
  `contact` varchar(400) NOT NULL,
  `course` varchar(400) NOT NULL,
  `city` varchar(400) NOT NULL,
  `email` varchar(400) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `entries`
--

INSERT INTO `entries` (`id`, `time`, `name`, `contact`, `course`, `city`, `email`) VALUES
(21, '2023-03-18 09:17:20', 'Anjaneya mishra', '8318293633', 'Btech', 'All over india', 'mishraanjaneya62@gmail.com'),
(22, '2023-03-18 09:17:20', 'Saurav kumar chaudhary', '9761840122', 'Bba', 'Mathura', 'sauravkumar202140@gmail.com'),
(23, '2023-03-18 09:17:20', 'Rahul Saini', '8849304556', 'PGDM', 'Faizabad, Uttar Pradesh.', 'rahulsaini2012@gmail.com'),
(24, '2023-03-18 09:17:20', 'Avinash Kumar jha ', '7761024761', 'BBA ', 'Darbhanga ', 'jha5112003@gmail.com'),
(25, '2023-03-18 09:17:20', 'Avinash Kumar jha ', '7761024761', 'BBA ', 'Darbhanga ', 'jha5112003@gmail.com'),
(26, '2023-03-18 09:17:20', 'Avinash Kumar jha ', '7761024761', 'BBA ', 'Darbhanga ', 'jha5112003@gmail.com'),
(34, '2023-03-18 09:23:20', 'dffdfd', '321312', 'sadsd', '2133213', 'ahammad.mustaq@gmail.com');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `college_details`
--
ALTER TABLE `college_details`
  ADD PRIMARY KEY (`ID`,`time`);

--
-- Indexes for table `entries`
--
ALTER TABLE `entries`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `college_details`
--
ALTER TABLE `college_details`
  MODIFY `ID` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=104;

--
-- AUTO_INCREMENT for table `entries`
--
ALTER TABLE `entries`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
